//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather_forecast
    {
        public int Id { get; set; }
        public double temperature { get; set; }
        public double max_temperature { get; set; }
        public double min_temperature { get; set; }
        public int humidity { get; set; }
        public int air_pressure { get; set; }
        public int wind_speed { get; set; }
        public int wind_direction { get; set; }
        public string icon { get; set; }
        public string main { get; set; }
        public int city_id { get; set; }
    
        public virtual City City { get; set; }
    }
}
